### ISSUE TITLE
Error:  undefined method `source' for nil:NilClass

### ISSUE THREAD

**Issue by hadrienj** [rfwatson/jekyll-stealthy-share#1]
Hi, 

I tried to use your plugin but I got this error message. I installed it with `bundle install` and then tried to start my dev server with `bundle exec jekyll serve --livereload`. Any idea?

Thanks
Hadrien

**Comment by rfwatson** [comment]
Hi @hadrienj!

A quick test in my dev environment with `--livereload` doesn't appear to recreate the issue.

Could you please provide the following information:

1. The full versions of Ruby and Jekyll that you're using (`ruby -v` and `bundle exec jekyll -v`)
1. The full backtrace from the exception that is triggered

**Comment by hadrienj** [comment]
Here are the versions:

`ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]`

and

`jekyll 3.7.3`

Here is the full message:

```
bundle exec jekyll serve --livereload

    Configuration file: /Users/lsp/Documents/projets/en_cours/blog-gh/blog/_config.yml

    Source: /Users/lsp/Documents/projets/en_cours/blog-gh/blog

    Destination: /Users/lsp/Documents/projets/en_cours/blog-gh/blog/_site

    Incremental build: disabled. Enable with --incremental

    Generating... 

    Liquid Exception: undefined method `source' for nil:NilClass in 

    /Users/lsp/Documents/projets/en_cours/blog-gh/blog/_posts/2018-03-26-Deep-Learning-Book-Series-Introduction.md

    jekyll 3.7.3 | Error:  undefined method `source' for nil:NilClass
```

**Comment by rfwatson** [comment]
Thanks @hadrienj.

One more request, if you run `bundle exec jekyll serve --livereload --trace`, could you post that output in full too please?

**Comment by hadrienj** [comment]
Here is the raw output:

```
bundle exec jekyll serve --livereload --trace
Configuration file: /Users/lsp/Documents/projets/en_cours/blog-gh/blog/_config.yml
            Source: /Users/lsp/Documents/projets/en_cours/blog-gh/blog
       Destination: /Users/lsp/Documents/projets/en_cours/blog-gh/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: undefined method `source' for nil:NilClass in /Users/lsp/Documents/projets/en_cours/blog-gh/blog/_posts/2018-03-26-Deep-Learning-Book-Series-2.5-Norms.md
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
NoMethodError: undefined method `source' for nil:NilClass
  /usr/local/lib/ruby/gems/2.5.0/bundler/gems/jekyll-stealthy-share-7215f5f41c72/lib/jekyll/stealthy_share.rb:29:in `source_templates_path'
  /usr/local/lib/ruby/gems/2.5.0/bundler/gems/jekyll-stealthy-share-7215f5f41c72/lib/jekyll/stealthy_share.rb:17:in `templates_path'
  /usr/local/lib/ruby/gems/2.5.0/bundler/gems/jekyll-stealthy-share-7215f5f41c72/lib/jekyll/stealthy_share/template.rb:21:in `all'
  /usr/local/lib/ruby/gems/2.5.0/bundler/gems/jekyll-stealthy-share-7215f5f41c72/lib/jekyll/stealthy_share/template.rb:9:in `basenames'
  /usr/local/lib/ruby/gems/2.5.0/bundler/gems/jekyll-stealthy-share-7215f5f41c72/lib/jekyll/stealthy_share/tag.rb:38:in `templates'
  /usr/local/lib/ruby/gems/2.5.0/bundler/gems/jekyll-stealthy-share-7215f5f41c72/lib/jekyll/stealthy_share/tag.rb:17:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:123:in `render_liquid'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:76:in `render_document'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/renderer.rb:62:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:462:in `block (2 levels) in render_docs'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:460:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:460:in `block in render_docs'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:459:in `each_value'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:459:in `render_docs'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:190:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:73:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:65:in `build'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:36:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `block in start'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
```

**Comment by rfwatson** [comment]
Hey Hadrien

Thanks for the stacktrace - it's really useful.

I can see what's going wrong now (I think that the `site` parameter [here](https://github.com/rfwatson/jekyll-stealthy-share/blob/7215f5f41c728dca97c7e1762d3e36ed9342367a/lib/jekyll/stealthy_share/generator.rb#L6) is being passed `nil`). Unfortunately I can't see _why_ this is happening on your machine. When I tried with a fresh Jekyll blog on the same Ruby/Jekyll versions it all worked fine for me. :thinking: 

Would you mind posting your `_config.yml` file to help me debug this further? (It might be worth checking that it doesn't contain any sensitive values first).

**Comment by hadrienj** [comment]
Hi,

You can find the blog [here](https://github.com/hadrienj/hadrienj.github.io) with the `_config.yml` and other files. The error is occurring when I add the plugin (in `_config.yml`, `Gemfile`... as showing in your readme).

Hope that helps.

**Comment by rfwatson** [comment]
Thanks @hadrienj  - I've managed to recreate this locally now. I should be able to take a deeper look over the next day or so. I'll keep you informed.

**Comment by hadrienj** [comment]
Nice! Thank you!

**Comment by rfwatson** [comment]
Hi @hadrienj 

Unfortunately, it turns out that [GitHub doesn't allow custom Jekyll plugins](https://stackoverflow.com/a/8648437/62871), and the `github-pages` gem seems to silently disable such plugins.

Obviously this isn't great news. The only thing I can suggest would be to host your blog elsewhere (I use Amazon S3 static website hosting, and [GitLab](https://docs.gitlab.com/ee/user/project/pages/) also offer Pages-type hosting. Neither of these limit Jekyll plugins.)
 
Note that the `github-pages` gem does allow you to [whitelist plugins for local testing only](https://github.com/github/pages-gem#bypassing-the-plugin-whitelist).

Sorry I can't be of more help.

**Comment by hadrienj** [comment]
Ok no worries, I understand! Thanks for your help!
